### ISSUE TITLE
怎样下载csv文件

### ISSUE THREAD

**Issue by Sony-1972** [acc8226/jiejian#1]
当我下载了data.csv和app.csv文件,他们都是乱码

**Comment by acc8226** [comment]
README.md 里面有说明。

![image](https://github.com/acc8226/jiejian/assets/10010627/c8e399aa-9d8b-4c11-aadd-1668bb8e292c)

由于我选择中文 GB18030 编码，当时我也在utf8 和 gbk 中纠结过，但是 windows 系统默认 cmd 都是中文编码最终选择了 gbk。

首先直接从 github 不会乱码，我通常会使用 [LiberOffice](https://www.libreoffice.org/download/download-libreoffice/) 进行编辑，开发中有时会用 vscode 打开。新版本的比如 word 2021 打开也是没问题的。相反的，不建议使用 wps 打开，保存的时候每次都会提示格式不兼容。

**Comment by acc8226** [comment]
> 当我下载了data.csv和app.csv文件,他们都是乱码

README.md 里面有说明。

![image](https://github.com/acc8226/jiejian/assets/10010627/c8e399aa-9d8b-4c11-aadd-1668bb8e292c)

由于我选择中文 GB18030 编码，当时我也在utf8 和 gbk 中纠结过，由于 windows 系统默认 cmd 都是中文编码我最终选择了国标。

我通常会使用 [LiberOffice](https://www.libreoffice.org/download/download-libreoffice/) 进行编辑，开发中有时会用 vscode 打开。新版本的比如 word 2021 打开也是没问题的。相反的，不建议使用 wps 打开，保存的时候每次都会提示格式不兼容。
